import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./responsive.scss";
import { ToastContainer } from "react-toastify";
import "react-toastify/ReactToastify.min.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children} <ToastContainer style={{ zIndex: "10000" }} />
      </body>
    </html>
  );
}
